# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from det.models.base_model_ import Model
from det.models.attribute_defs_item import AttributeDefsItem  # noqa: F401,E501
from det import util


class ClassificationDefsItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, category=None, name=None, description=None, super_types=None, attribute_defs=None):  # noqa: E501
        """ClassificationDefsItem - a model defined in Swagger

        :param category: The category of this ClassificationDefsItem.  # noqa: E501
        :type category: str
        :param name: The name of this ClassificationDefsItem.  # noqa: E501
        :type name: str
        :param description: The description of this ClassificationDefsItem.  # noqa: E501
        :type description: str
        :param super_types: The super_types of this ClassificationDefsItem.  # noqa: E501
        :type super_types: List[str]
        :param attribute_defs: The attribute_defs of this ClassificationDefsItem.  # noqa: E501
        :type attribute_defs: List[AttributeDefsItem]
        """
        self.swagger_types = {
            'category': str,
            'name': str,
            'description': str,
            'super_types': List[str],
            'attribute_defs': List[AttributeDefsItem]
        }

        self.attribute_map = {
            'category': 'category',
            'name': 'name',
            'description': 'description',
            'super_types': 'superTypes',
            'attribute_defs': 'attributeDefs'
        }

        self._category = category
        self._name = name
        self._description = description
        self._super_types = super_types
        self._attribute_defs = attribute_defs

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClassificationDefsItem of this ClassificationDefsItem.  # noqa: E501
        :rtype: ClassificationDefsItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self):
        """Gets the category of this ClassificationDefsItem.


        :return: The category of this ClassificationDefsItem.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ClassificationDefsItem.


        :param category: The category of this ClassificationDefsItem.
        :type category: str
        """
        allowed_values = ["CLASSIFICATION"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def name(self):
        """Gets the name of this ClassificationDefsItem.


        :return: The name of this ClassificationDefsItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ClassificationDefsItem.


        :param name: The name of this ClassificationDefsItem.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ClassificationDefsItem.


        :return: The description of this ClassificationDefsItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ClassificationDefsItem.


        :param description: The description of this ClassificationDefsItem.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def super_types(self):
        """Gets the super_types of this ClassificationDefsItem.


        :return: The super_types of this ClassificationDefsItem.
        :rtype: List[str]
        """
        return self._super_types

    @super_types.setter
    def super_types(self, super_types):
        """Sets the super_types of this ClassificationDefsItem.


        :param super_types: The super_types of this ClassificationDefsItem.
        :type super_types: List[str]
        """

        self._super_types = super_types

    @property
    def attribute_defs(self):
        """Gets the attribute_defs of this ClassificationDefsItem.


        :return: The attribute_defs of this ClassificationDefsItem.
        :rtype: List[AttributeDefsItem]
        """
        return self._attribute_defs

    @attribute_defs.setter
    def attribute_defs(self, attribute_defs):
        """Sets the attribute_defs of this ClassificationDefsItem.


        :param attribute_defs: The attribute_defs of this ClassificationDefsItem.
        :type attribute_defs: List[AttributeDefsItem]
        """

        self._attribute_defs = attribute_defs
