# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from det.models.base_model_ import Model
from det import util


class HdfsMaintenanceServiceItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ALL = "all"
    ARCHIVE = "archive"
    PURGE = "purge"
    COMPRESS = "compress"

    def __init__(self):  # noqa: E501
        """HdfsMaintenanceServiceItem - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'HdfsMaintenanceServiceItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HdfsMaintenanceServiceItem of this HdfsMaintenanceServiceItem.  # noqa: E501
        :rtype: HdfsMaintenanceServiceItem
        """
        return util.deserialize_model(dikt, cls)
