# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from det.models.base_model_ import Model
from det.models.environments import Environments  # noqa: F401,E501
from det.models.hdfs_path_item_classification import HdfsPathItemClassification  # noqa: F401,E501
from det import util


class HdfsPathItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, data_code: str=None, env: Environments=None, delivery_ingestion: str=None, app: str=None, subfolder: str=None, classification: HdfsPathItemClassification=None):  # noqa: E501
        """HdfsPathItem - a model defined in Swagger

        :param data_code: The data_code of this HdfsPathItem.  # noqa: E501
        :type data_code: str
        :param env: The env of this HdfsPathItem.  # noqa: E501
        :type env: Environments
        :param delivery_ingestion: The delivery_ingestion of this HdfsPathItem.  # noqa: E501
        :type delivery_ingestion: str
        :param app: The app of this HdfsPathItem.  # noqa: E501
        :type app: str
        :param subfolder: The subfolder of this HdfsPathItem.  # noqa: E501
        :type subfolder: str
        :param classification: The classification of this HdfsPathItem.  # noqa: E501
        :type classification: HdfsPathItemClassification
        """
        self.swagger_types = {
            'data_code': str,
            'env': Environments,
            'delivery_ingestion': str,
            'app': str,
            'subfolder': str,
            'classification': HdfsPathItemClassification
        }

        self.attribute_map = {
            'data_code': 'data_code',
            'env': 'env',
            'delivery_ingestion': 'delivery_ingestion',
            'app': 'app',
            'subfolder': 'subfolder',
            'classification': 'classification'
        }

        self._data_code = data_code
        self._env = env
        self._delivery_ingestion = delivery_ingestion
        self._app = app
        self._subfolder = subfolder
        self._classification = classification

    @classmethod
    def from_dict(cls, dikt) -> 'HdfsPathItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HdfsPathItem of this HdfsPathItem.  # noqa: E501
        :rtype: HdfsPathItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_code(self) -> str:
        """Gets the data_code of this HdfsPathItem.


        :return: The data_code of this HdfsPathItem.
        :rtype: str
        """
        return self._data_code

    @data_code.setter
    def data_code(self, data_code: str):
        """Sets the data_code of this HdfsPathItem.


        :param data_code: The data_code of this HdfsPathItem.
        :type data_code: str
        """
        allowed_values = ["data"]  # noqa: E501
        if data_code not in allowed_values:
            raise ValueError(
                "Invalid value for `data_code` ({0}), must be one of {1}"
                .format(data_code, allowed_values)
            )

        self._data_code = data_code

    @property
    def env(self) -> Environments:
        """Gets the env of this HdfsPathItem.


        :return: The env of this HdfsPathItem.
        :rtype: Environments
        """
        return self._env

    @env.setter
    def env(self, env: Environments):
        """Sets the env of this HdfsPathItem.


        :param env: The env of this HdfsPathItem.
        :type env: Environments
        """
        if env is None:
            raise ValueError("Invalid value for `env`, must not be `None`")  # noqa: E501

        self._env = env

    @property
    def delivery_ingestion(self) -> str:
        """Gets the delivery_ingestion of this HdfsPathItem.


        :return: The delivery_ingestion of this HdfsPathItem.
        :rtype: str
        """
        return self._delivery_ingestion

    @delivery_ingestion.setter
    def delivery_ingestion(self, delivery_ingestion: str):
        """Sets the delivery_ingestion of this HdfsPathItem.


        :param delivery_ingestion: The delivery_ingestion of this HdfsPathItem.
        :type delivery_ingestion: str
        """
        allowed_values = ["delivery", "ingestion"]  # noqa: E501
        if delivery_ingestion not in allowed_values:
            raise ValueError(
                "Invalid value for `delivery_ingestion` ({0}), must be one of {1}"
                .format(delivery_ingestion, allowed_values)
            )

        self._delivery_ingestion = delivery_ingestion

    @property
    def app(self) -> str:
        """Gets the app of this HdfsPathItem.


        :return: The app of this HdfsPathItem.
        :rtype: str
        """
        return self._app

    @app.setter
    def app(self, app: str):
        """Sets the app of this HdfsPathItem.


        :param app: The app of this HdfsPathItem.
        :type app: str
        """
        if app is None:
            raise ValueError("Invalid value for `app`, must not be `None`")  # noqa: E501

        self._app = app

    @property
    def subfolder(self) -> str:
        """Gets the subfolder of this HdfsPathItem.


        :return: The subfolder of this HdfsPathItem.
        :rtype: str
        """
        return self._subfolder

    @subfolder.setter
    def subfolder(self, subfolder: str):
        """Sets the subfolder of this HdfsPathItem.


        :param subfolder: The subfolder of this HdfsPathItem.
        :type subfolder: str
        """

        self._subfolder = subfolder

    @property
    def classification(self) -> HdfsPathItemClassification:
        """Gets the classification of this HdfsPathItem.


        :return: The classification of this HdfsPathItem.
        :rtype: HdfsPathItemClassification
        """
        return self._classification

    @classification.setter
    def classification(self, classification: HdfsPathItemClassification):
        """Sets the classification of this HdfsPathItem.


        :param classification: The classification of this HdfsPathItem.
        :type classification: HdfsPathItemClassification
        """
        if classification is None:
            raise ValueError("Invalid value for `classification`, must not be `None`")  # noqa: E501

        self._classification = classification
