# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from det.models.base_model_ import Model
from det import util


class Retainable(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """Retainable - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Retainable':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Retainable of this Retainable.  # noqa: E501
        :rtype: Retainable
        """
        return util.deserialize_model(dikt, cls)
