# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HdfsPathItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, datacode=None):  # noqa: E501
        """HdfsPathItem - a model defined in Swagger

        :param datacode: The datacode of this HdfsPathItem.  # noqa: E501
        :type datacode: str
        """
        self.swagger_types = {
            'datacode': str
        }

        self.attribute_map = {
            'datacode': 'datacode'
        }

        self._datacode = datacode

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HdfsPathItem of this HdfsPathItem.  # noqa: E501
        :rtype: HdfsPathItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datacode(self):
        """Gets the datacode of this HdfsPathItem.


        :return: The datacode of this HdfsPathItem.
        :rtype: str
        """
        return self._datacode

    @datacode.setter
    def datacode(self, datacode):
        """Sets the datacode of this HdfsPathItem.


        :param datacode: The datacode of this HdfsPathItem.
        :type datacode: str
        """
        allowed_values = ["data", "code"]  # noqa: E501
        if datacode not in allowed_values:
            raise ValueError(
                "Invalid value for `datacode` ({0}), must be one of {1}"
                .format(datacode, allowed_values)
            )

        self._datacode = datacode
