# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.environments import Environments  # noqa: F401,E501
from swagger_server.models.hdfs_path_item_classification import HdfsPathItemClassification  # noqa: F401,E501
from swagger_server import util


class HdfsPathItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, datacode=None, env=None, delivery_ingestion=None, classification=None):  # noqa: E501
        """HdfsPathItem - a model defined in Swagger

        :param datacode: The datacode of this HdfsPathItem.  # noqa: E501
        :type datacode: str
        :param env: The env of this HdfsPathItem.  # noqa: E501
        :type env: Environments
        :param delivery_ingestion: The delivery_ingestion of this HdfsPathItem.  # noqa: E501
        :type delivery_ingestion: str
        :param classification: The classification of this HdfsPathItem.  # noqa: E501
        :type classification: HdfsPathItemClassification
        """
        self.swagger_types = {
            'datacode': str,
            'env': Environments,
            'delivery_ingestion': str,
            'classification': HdfsPathItemClassification
        }

        self.attribute_map = {
            'datacode': 'datacode',
            'env': 'env',
            'delivery_ingestion': 'delivery_ingestion',
            'classification': 'classification'
        }

        self._datacode = datacode
        self._env = env
        self._delivery_ingestion = delivery_ingestion
        self._classification = classification

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HdfsPathItem of this HdfsPathItem.  # noqa: E501
        :rtype: HdfsPathItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datacode(self):
        """Gets the datacode of this HdfsPathItem.


        :return: The datacode of this HdfsPathItem.
        :rtype: str
        """
        return self._datacode

    @datacode.setter
    def datacode(self, datacode):
        """Sets the datacode of this HdfsPathItem.


        :param datacode: The datacode of this HdfsPathItem.
        :type datacode: str
        """
        allowed_values = ["data"]  # noqa: E501
        if datacode not in allowed_values:
            raise ValueError(
                "Invalid value for `datacode` ({0}), must be one of {1}"
                .format(datacode, allowed_values)
            )

        self._datacode = datacode

    @property
    def env(self):
        """Gets the env of this HdfsPathItem.


        :return: The env of this HdfsPathItem.
        :rtype: Environments
        """
        return self._env

    @env.setter
    def env(self, env):
        """Sets the env of this HdfsPathItem.


        :param env: The env of this HdfsPathItem.
        :type env: Environments
        """
        if env is None:
            raise ValueError("Invalid value for `env`, must not be `None`")  # noqa: E501

        self._env = env

    @property
    def delivery_ingestion(self):
        """Gets the delivery_ingestion of this HdfsPathItem.


        :return: The delivery_ingestion of this HdfsPathItem.
        :rtype: str
        """
        return self._delivery_ingestion

    @delivery_ingestion.setter
    def delivery_ingestion(self, delivery_ingestion):
        """Sets the delivery_ingestion of this HdfsPathItem.


        :param delivery_ingestion: The delivery_ingestion of this HdfsPathItem.
        :type delivery_ingestion: str
        """
        allowed_values = ["delivery", "ingestion"]  # noqa: E501
        if delivery_ingestion not in allowed_values:
            raise ValueError(
                "Invalid value for `delivery_ingestion` ({0}), must be one of {1}"
                .format(delivery_ingestion, allowed_values)
            )

        self._delivery_ingestion = delivery_ingestion

    @property
    def classification(self):
        """Gets the classification of this HdfsPathItem.


        :return: The classification of this HdfsPathItem.
        :rtype: HdfsPathItemClassification
        """
        return self._classification

    @classification.setter
    def classification(self, classification):
        """Sets the classification of this HdfsPathItem.


        :param classification: The classification of this HdfsPathItem.
        :type classification: HdfsPathItemClassification
        """

        self._classification = classification
