{% set data = load_setup_py_data() %}

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}

source:
  path: ../

package:
  name: det
  version: {{ data['version'] }}

requirements:
  build: 
    - python
    - setuptools
    - pytest-runner
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

  run: 
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - det
